### PR TITLE
Profile Card: Display Name Population / Updating

### PR DESCRIPTION
**Pull request by LouisLP**
# Submodule

Main repo PR:
https://github.com/UBCO-COSC-499-Summer-2023/PrairieLearn-Gamification/pull/328

A student should be able to:
- See their display name on the top of the profile card
- Change their display name using AJAX
- View their achieved achievements (badges)

This PR is meant to address the first two. Scroll below for more details on where I'm at...

### CODE REVIEW

**Comment by LouisLP** [comment]
The current student's display name is displayed on top of their profile card...

image

**Comment by LouisLP** [comment]
However, I'm getting an error when trying to change/update their display name.
Because the route for student is different than plrStaff, I'm wondering if we have to use another type of CSRF token?

image

**Comment by LouisLP** [comment]
The PrairieLearn devs [shared some more wisdom here](https://prairielearn.slack.com/archives/C266KEH9A/p1690683795536769), but despite that, updating display names still doesn't work.
I'm 95% sure the URLs are the same (which allows the CSRF token to be passed), so I'm not understanding what else is missing. They were putting the token in the body rather than the headers, but maybe I should remove it altogether? 

In addition, Rylan was saying the placement of the `plrStudent` nav element matters in `server.js`, so I moved it down to line 1400 (with all the other student stuff). Doing that caused the page to not load properly, so I added a bandaid fix to `plrStudent.js` which sets the `navPage` value.

**Comment by LouisLP** [comment]
It works (by reloading the page through a POST, rather than trying to get ASYNC to work)
image

**Comment by LouisLP** [comment]
Working on adding a list of prohibited words now.

**Comment by LouisLP** [comment]
If you try to type a word on the list of profanities as your display name, you get redirected back to the original page (without the change).
image

**Review by S-Patel25 — APPROVED** [review]
LOOKS GOOD TO ME!

**Pull request merged**
