### PR TITLE
Frontend Polish (ROUND 1)

### PR DESCRIPTION
**Pull request by LouisLP**
# Sub-Repo

Link to main repo's PR: https://github.com/UBCO-COSC-499-Summer-2023/PrairieLearn-Gamification/pull/336

### CODE REVIEW

**Comment by LouisLP** [comment]
Here's what our widescreen layout looks like on plrStudent:
image

And plrStaff:
image

**Comment by LouisLP** [comment]
I made it so that when the window is half the size of a normal monitor, the side-cards pop down below.
This was especially needed because the "all-time scoreboard" had too many columns, and you'd have to horizontally scroll if the window was too small.

image

**Comment by RylanRCox** [comment]
image
Running it on mine I'm getting this weird ugly scrollbar. Is there a way to remove that?

Also, can we remove the join live session button on the student page? As it serves no purpose anymore.

**Comment by RylanRCox** [comment]
image
Also running the staff page and clicking on the buttons. There is no population within the DB and the colouring state does not remain.

**Review by S-Patel25 — CHANGES_REQUESTED** [review]
UI Looks good, but in previous message Rylan mentioned DB is not populating?

**Comment by LouisLP** [comment]
- Remove scrollbar (or style it darker) on scoreboards
- Remove "join live session" button on plrStudent
- Make sure the button is actually starting a live session (might've removed the ID/class that caused it to link up)

**Review by S-Patel25 — APPROVED** [review]
Looks good to me!

**Comment by LouisLP** [comment]
Instructors now have the option to go fullscreen mode (basically a "presenter" mode)
image

**Comment by LouisLP** [comment]
Even on page reload, it now uses local storage to check if the button was clicked beforehand.
image

**Review by S-Patel25 — APPROVED** [review]
GREAT WORK!

**Pull request merged**
